# Generated by Django 6.0.3 on 2026-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_chat_id', models.BigIntegerField(blank=True, help_text='ID группы/чата для уведомлений о заказах и управления статусами', null=True)),
                ('admin_telegram_ids', models.JSONField(blank=True, default=list, help_text='Список telegram_id админов (для команды /orders и смены статуса из чата)')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
                'db_table': 'bot_settings_botsettings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('invite_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Канал подписки',
                'verbose_name_plural': 'Каналы подписки',
                'db_table': 'bot_settings_subscriptionchannel',
                'ordering': ['order'],
            },
        ),
    ]
