# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcasts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("text", models.TextField(verbose_name="Текст (HTML как в Telegram)")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="broadcast_templates/%Y/%m/",
                        verbose_name="Картинка",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Шаблон рассылки",
                "verbose_name_plural": "Шаблоны рассылок",
                "db_table": "broadcasts_broadcasttemplate",
                "ordering": ["order", "id"],
            },
        ),
    ]
